# Generated by Django 4.2.7 on 2023-12-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200118_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='diseaseinfo',
            name='symptomsname',
        ),
        migrations.AddField(
            model_name='diseaseinfo',
            name='symptoms',
            field=models.ManyToManyField(to='main_app.symptom'),
        ),
    ]
