# Generated by Django 4.2.7 on 2023-12-15 16:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_symptom_remove_diseaseinfo_symptomsname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaseinfo',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='diseaseinfo',
            name='symptomsname',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
